version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
    restart: unless-stopped
    networks:
      - elastic
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    restart: unless-stopped
    networks:
      - elastic
    depends_on:
      - elasticsearch

  blazegraph:
    build:
      context: ./blazegraph
    container_name: blazegraph
    ports:
      - "9999:9999"
    restart: unless-stopped

networks:
  elastic:
    driver: bridge